# Generated by Django 3.2.8 on 2022-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
