# Generated by Django 3.2.8 on 2022-08-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_proyecto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonios')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
