# Generated by Django 3.2.9 on 2022-08-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220817_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='estado',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
