# Generated by Django 3.2.9 on 2022-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_testimoni_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios'),
        ),
    ]
